export const UserActionTypes={
    FETCH_ROBOTS_START:'FETCH_ROBOTS_START',
    FETCH_ROBOTS_SUCCESS:'FETCH_ROBOTS_SUCCESS',
    FETCH_ROBOTSFAILURE:'FETCH_ROBOTS_FAILURE',
    ADD_ROBOTS_START:'ADD_ROBOTS_START',
    ADD_ROBOTS_SUCCESS:'ADD_ROBOTS_SUCCESS',
    ADD_ROBOTS_FAILURE:'ADD_ROBOTS_FAILURE',
    DELETE_ROBOTS_START:'DELETE_ROBOTS_START',
}